nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  babel-preset-expo@*:
    peerDependencies:
      "@babel/core": ^7.13.0
  expo@*:
    peerDependencies:
      "@babel/core": ^7.13.0
  react-native-codegen@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  react-native@*:
    peerDependencies:
      "@babel/preset-env": ^7.1.6
  